# Production Docker Compose Override
# Usage: docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d

version: '3.8'

services:
  postgres:
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'
    # Remove port exposure in production
    ports: []
    environment:
      # Production database settings
      POSTGRES_SHARED_PRELOAD_LIBRARIES: "pg_stat_statements,pg_buffercache"
    command: >
      postgres
      -c config_file=/etc/postgresql/postgresql.conf
      -c hba_file=/etc/postgresql/pg_hba.conf

  keycloak-prod:
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '2.0'
        reservations:
          memory: 1G
          cpus: '1.0'
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      # Production JVM settings
      JAVA_OPTS_APPEND: >-
        -Xms1g -Xmx2g
        -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m
        -XX:+UseG1GC
        -XX:MaxGCPauseMillis=200
        -XX:ParallelGCThreads=4
        -XX:ConcGCThreads=1
        -XX:+UseStringDeduplication
        -XX:+UseCompressedOops
        -XX:+DisableExplicitGC
        -Djava.net.preferIPv4Stack=true
        -Dfile.encoding=UTF-8
        -Djava.security.egd=file:/dev/urandom
        -XX:+HeapDumpOnOutOfMemoryError
        -XX:HeapDumpPath=/opt/keycloak/data/heap_dump.hprof
    # Production-specific volumes
    volumes:
      - ./config/realms:/opt/keycloak/data/import:ro
      - ./themes:/opt/keycloak/themes:ro
      - keycloak_data:/opt/keycloak/data
      - ./certs:/opt/keycloak/certs:ro  # Mount SSL certificates
      - ./config/cache-ispn-jdbc-ping.xml:/opt/keycloak/conf/cache-ispn-jdbc-ping.xml:ro

volumes:
  keycloak_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /var/lib/keycloak
  postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /var/lib/postgresql/data